# example netlify.toml
[build]
  command = "nuxt generate"
  functions = "netlify/functions"
  publish = "dist"

[[redirects]]
  from = "/api/films"
  to = "/.netlify/functions/films"
  status = 200
  force = true

[[redirects]]
  from = "/api/images"
  to = "/.netlify/functions/film-image"
  status = 200
  force = true
