# example netlify.toml
[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[[redirects]]
  from = "/api/films"
  to = "/.netlify/functions/films"
  status = 200
  force = true

[[redirects]]
  from = "/api/images"
  to = "/.netlify/functions/film-image"
  status = 200
  force = true

[[redirects]]
  from = "/api/score/*"
  to = "/.netlify/functions/score-:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/admin/*"
  to = "/.netlify/functions/admin-:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
